### ISSUE TITLE
already initialized constant TBLENCWWWCOMP_

### ISSUE THREAD

**Issue by jlecour** [karmi/retire#690]
Hi,

When using Tire (`0.5.4`) in a Rails app (`3.2.12`) with Rack (`1.4.5`) I get this warning at every rake task execution and Rails boot : 

```
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/rack-1.4.5/lib/rack/backports/uri/common_18.rb:10: warning: already initialized constant TBLENCWWWCOMP_
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/rack-1.4.5/lib/rack/backports/uri/common_18.rb:16: warning: already initialized constant TBLDECWWWCOMP_
```

Isn't there a way to not redefine `URI` if it's already defined ?

Thanks

**Comment by karmi** [comment]
This has been fixed in fb9b6fa, could you upgrade?

**Comment by jlecour** [comment]
It is really strange.

If I use the gem package, it works, I don't have the waning.
But if I use the GitHub version of the gem, I still get the warning.

I've triple-checked the source code each time.

**Comment by karmi** [comment]
Are you absolutely sure the right version is picked up? Notice that with `gem "tire", git: "..."` you have to run `bundle update tire` to pick up changes. Use `bundle show tire` to print information about the version used.

**Comment by jlecour** [comment]
here is what I have : 

```
→ cat Gemfile | grep tire
gem 'tire', :github => 'karmi/tire'

→ cat Gemfile.lock | grep tire
  remote: git://github.com/karmi/tire.git
    tire (0.5.7)
  tire!

→ bundle show tire
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/bundler/gems/tire-c35028539c33

→ cat /usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/bundler/gems/tire-c35028539c33/lib/tire/rubyext/ruby_1_8.rb
require 'tire/rubyext/uri_escape' unless defined?(URI.encode_www_form_component) && defined?(URI.decode_www_form_component)
```

So I guess I have the right source code in my bundle, since the content of that file matches the fb9b6fa commit.

Then, with `rake` : 

```
→ bin/rake routes
/Users/jlecour/Projects/my_app/bin
(in /Users/jlecour/Projects/my_app)
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/rack-1.4.5/lib/rack/backports/uri/common_18.rb:10: warning: already initialized constant TBLENCWWWCOMP_
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/rack-1.4.5/lib/rack/backports/uri/common_18.rb:16: warning: already initialized constant TBLDECWWWCOMP_
(snipped routes)
```

The I use the gemified version of Tire : 

```
→ cat Gemfile | grep tire
gem 'tire', '~> 0.5.7'

→ cat Gemfile.lock | grep tire
    tire (0.5.7)
  tire (~> 0.5.7)

→ bundle show tire
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/tire-0.5.7

→ cat /usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/tire-0.5.7/lib/tire/rubyext/ruby_1_8.rb
require 'tire/rubyext/uri_escape' unless defined?(URI.encode_www_form_component) && defined?(URI.decode_www_form_component)
```

And then I don't understand because `rake` still has those warnings. Yesterday, when I did the same it didn't output them.

The fact is that even with this conditional requirement, there is something wrong, at least on my side, and I don't get it.

I'll try again with a blank slate and report the results. In the mean time, if you have any idea why this hapens, I'm all ears.

Thanks

**Comment by jlecour** [comment]
I removed Tire from my Gemfile and comment the initializer (with the configuration), so obviously I didn't get any warning.

Then I enabled Tire back in the Gemfile, but this time, I've edited the `lib/tire/rubyext/ruby_1_8.rb` (which is located in `/usr/local/var/lib/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/tire-0.5.7/`) and changed this : 

``` ruby
require 'tire/rubyext/uri_escape' unless defined?(URI.encode_www_form_component) && defined?(URI.decode_www_form_component)`
```

to this : 

``` ruby
raise 'tire/rubyext/uri_escape'.inspect unless defined?(URI.encode_www_form_component) && defined?(URI.decode_www_form_component)
```

The idea was to verify explicitly that the conditions was passing or not.

When I started my app, or ran a rake task, I got this :

```
→ bin/rake routes --trace
/Users/jlecour/Projects/my_app/bin
(in /Users/jlecour/Projects/my_app)
rake aborted!
"tire/rubyext/uri_escape"
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/tire-0.5.7/lib/tire/rubyext/ruby_1_8.rb:1
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/tire-0.5.7/lib/tire.rb:13:in `require'
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/tire-0.5.7/lib/tire.rb:13
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/bundler-1.3.1/lib/bundler/runtime.rb:72:in `require'
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/bundler-1.3.1/lib/bundler/runtime.rb:72:in `require'
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/bundler-1.3.1/lib/bundler/runtime.rb:70:in `each'
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/bundler-1.3.1/lib/bundler/runtime.rb:70:in `require'
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/bundler-1.3.1/lib/bundler/runtime.rb:59:in `each'
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/bundler-1.3.1/lib/bundler/runtime.rb:59:in `require'
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/bundler-1.3.1/lib/bundler.rb:132:in `require'
/Users/jlecour/Projects/my_app/config/application.rb:10
/Users/jlecour/Projects/my_app/Rakefile:4:in `require'
/Users/jlecour/Projects/my_app/Rakefile:4
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2383:in `load'
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2383:in `raw_load_rakefile'
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2017:in `load_rakefile'
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2016:in `load_rakefile'
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2000:in `run'
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/usr/local/opt/rbenv/versions/1.8.7-p371/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
bin/rake:16:in `load'
bin/rake:16
```

Since the raise is executed, I guess the condition on URI methods returns `false`, when it should return `true` (Rack being already loaded).

**Comment by jlecour** [comment]
Got it !

The position `gem 'tire'` in the `Gemfile` matters.

I've always had it just after `rails` and `rake`. I've moved it at the bottom of the `Gemfile`, and it worked.

Then I've tried to narrow this down, and the conclusion is (in my case) : it has to be after `Unicorn`.
It's strange because `Rails` is requiring `Rack`, but maybe not the part that we are talking about.

After all this dancing around, I'm able to use the gemified version of Tire, as well as the GitHub version, or my own fork, without any issue.

Maybe there is something to do with this, in the documentation, or in the code itself, but I have no idea what.

That was fun, regardless of the time spent/lost on this issue.
Thanks for your support.

**Comment by karmi** [comment]
Phew, in a slightly crazy meaning of "fun", I think this could be a large dose of it :)

I'm not aware of any reason why it would be so -- note, that in the current version, we don't require the file from Rack, but rather a [physical file](https://github.com/karmi/tire/blob/master/lib/tire/rubyext/uri_escape.rb) in Tire codebase itself... Tried to replicate the issue, but I can include Unicorn before Tire just fine...

**Comment by jlecour** [comment]
I know that the file is required from Tire itself, but before that it checks whether some methods are available in the `URI` namespace. Usually they are in that namespace thanks to `Rack`.

I've made a bare Rails app, to exclude context as much as possible.

With this `Gemfile`, it works : 

``` ruby
source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'sqlite3'
gem 'unicorn', '~> 4.6.2'
gem 'tire', '~> 0.5.7'
```

But with this one, I get the warnings : 

``` ruby
source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'sqlite3'
gem 'tire', '~> 0.5.7'
gem 'unicorn', '~> 4.6.2'
```

I've tried with Unicorn 4.5.0, but the results are the same.

If I replace Unicorn by Thin, it works both ways.

I remain deeply puzzled ;)
