### ISSUE TITLE
While importing, percentage complete exceeds 100%

### ISSUE THREAD

**Issue by jpsilvashy** [karmi/retire#84]
Upon running import for my model like so:

```
rake environment tire:import CLASS='Recipe.all' INDEX='mongo-recipes' FORCE=1 RAILS_ENV='production'
```

I receive some strange behavior resulting in a failure to import the model completely. 

```
** Invoke environment (first_time)
** Execute environment
** Invoke tire:import (first_time)
** Execute tire:import
#2011-08-30 08:00:05:130 [DELETE] ("mongo-recipes")
#
curl -X DELETE "http://localhost:9200/mongo-recipes"

#2011-08-30 08:00:05:130 [200]

#2011-08-30 08:00:05:173 [CREATE] ("mongo-recipes")
#
curl -X POST "http://localhost:9200/mongo-recipes" -d '{"mappings":{"recipe":{"properties":{"title":{"type":"string","analyzer":"snowball","boost":100},"description":{"type":"string","analyzer":"snowball","include_in_all":false},"tags":{"type":"array"},"id":{"type":"string"}}}}}'

#2011-08-30 08:00:05:173 [200]

[IMPORT] Deleting index 'mongo-recipes'
[IMPORT] Creating index 'mongo-recipes' with mapping:
{"recipe":{"properties":{"title":{"type":"string","analyzer":"snowball","boost":100},"description":{"type":"string","analyzer":"snowball","include_in_all":false},"tags":{"type":"array"},"id":{"type":"string"}}}}
[IMPORT] Starting import for the 'Recipe.all' class
--------------------------------------------------------------------------------
26733/26733 | 100% # 2011-08-30 08:00:07:840 [BULK] ("mongo-recipes")
#
curl -X POST "http://localhost:9200/_bulk" -d '{... data omitted ...}'

#2011-08-30 08:00:07:841 [200]

53466/26733 | 200% # 2011-08-30 08:00:10:872 [BULK] ("mongo-recipes")#######################################################
#
curl -X POST "http://localhost:9200/_bulk" -d '{... data omitted ...}'

#2011-08-30 08:00:10:872 [200]

80199/26733 | 300% # 2011-08-30 08:00:14:477 [BULK] ("mongo-recipes")#####################################################################################################################
#
curl -X POST "http://localhost:9200/_bulk" -d '{... data omitted ...}'
```

Eventually this grows to about 2400% and dies with:

```
curl -X POST "http://localhost:9200/_bulk" -d '{... data omitted ...}'

#2011-08-30 08:02:07:359 [200]

#####################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################695058/26733 | 2600% rake aborted!
too much data for sort() with no index.  add an index or specify a smaller limit
```

This behavior is really really strange, besides actually being larger than 100% complete, I figured I had all the right indexes for that model... Not sure really where to even start with this one, but would love to help tackle this bug regardless.

Thoughts?

**Comment by karmi** [comment]
Yeah. It's because for whatever reason, Mongoid is reporting `false` for `documents.empty?` in https://github.com/karmi/tire/blob/master/lib/tire/index.rb#L108.

**Comment by karmi** [comment]
This: karmi/tire@8d592e7 is the culprit why it broke: `will_paginate` needs a check for `#empty?`, _Kaminari_ needs a check for `#size > 0`.

Should be fixed now, `#length` seems to work for both. Could you verify it?

**Comment by jpsilvashy** [comment]
hmm.. I'm still having the issue, I think I should switch back to `will_paginate` from Kaminari, which pagination gem do you prefer? I should probably stick with what you know works. This maybe a non-issue all together.
